spring:
  application:
    name: elastiflix-java
  thymeleaf:
    cache: false
    encoding: UTF-8

server:
  port: 8080

elasticsearch:
  host: https://bigfito-serverless-search-a43f10.es.us-central1.gcp.elastic.cloud
  api-key: TnNRdXhwMEI3X2dZMnRSdWVKV3g6dG5PaWVaZ1dJOExZS2IybXZwYnZwZw==
  index: elastiflix-movies
  ssl-verify: false

app:
  page-size: 50
  tmdb-image-base: https://image.tmdb.org/t/p/w500
